# See LICENSE for license details.
set name {TR4}
set FAMILY "Stratix IV"
set part_fpga {EP4SGX230KF40C2}
set part_board {TR4}
set bootrom_inst {rom}
set MIN_CORE_JUNCTION_TEMP 0
set MAX_CORE_JUNCTION_TEMP 85
set ERROR_CHECK_FREQUENCY_DIVISOR 256
set POWER_PRESET_COOLING_SOLUTION "23 MM HEAT SINK WITH 200 LFPM AIRFLOW"
set POWER_BOARD_THERMAL_MODEL "NONE (CONSERVATIVE)"

