# See LICENSE for license details.
set name {Arrow}
set FAMILY "Cyclone V"
set part_fpga {5CSXFC6D6F31C6}
set part_board {Arrow}
set bootrom_inst {rom}
set MIN_CORE_JUNCTION_TEMP 0
set MAX_CORE_JUNCTION_TEMP 85
set ERROR_CHECK_FREQUENCY_DIVISOR 256
set POWER_PRESET_COOLING_SOLUTION "23 MM HEAT SINK WITH 200 LFPM AIRFLOW"
set POWER_BOARD_THERMAL_MODEL "NONE (CONSERVATIVE)"

